// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "Hidden/Preview 2D Texture Array"
{
    Properties
    {
        _MainTex ("Texture", 2DArray) = "" {}
        _SliceIndex ("Slice", Float) = 0
        _Mip ("Mip level", Float) = 0
        _ToSRGB ("", Float) = 0
        _IsNormalMap ("", Float) = 0
        _Exposure ("Exposure", Float) = 0
    }

    SubShader
    {
        Pass
        {
            Blend SrcAlpha OneMinusSrcAlpha
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                int _SliceIndex;
                float3 cb0_pad_36;
            
            cbuffer UnityPerDraw : register(b1) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b2) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return float4(_SliceIndex, 0.0f, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float3 o1 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb1[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: itof o1.z, cb0[2].x
                o1.z = (float)(_SliceIndex);
                //    9: mov o1.xy, v1.xyxx
                o1.xy = v1.xy;
                //   10: ret
                output.o0 = o0;
                output.o1 = o1.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1.xyz;
                return output;
            }

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float cb0_pad_32;
                int _Mip;
                int _ColorMaskBits;
                int _IsNormalMap;
                float _Exposure;
                int _ToSRGB;
                float2 cb0_pad_56;
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return float4(0.0f, _Mip, _ColorMaskBits, _IsNormalMap);
                    case 3: return float4(_Exposure, _ToSRGB, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            Texture2DArray _MainTex : register(t0);
            SamplerState sampler_MainTex : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float3 v1 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyz = input.v1;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r2_0 = (float4)0;
                float4 r2_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: itof r0.x, cb0[2].y
                r0_0.x = (float)(_Mip);
                //    1: sample_l r0.xyzw, v1.xyzx, t0.xyzw, s0, r0.x
                r0_1 = _MainTex.SampleLevel(sampler_MainTex, v1.xyz, r0_0.x);
                //    2: mul r1.x, r0.w, r0.x
                r1_0.x = r0_1.x * r0_1.w;
                //    3: mov r1.y, r0.y
                r1_0.y = r0_1.y;
                //    4: mad r1.xy, r1.xyxx, l(2.000000, 2.000000, 0.000000, 0.000000), l(-1.000000, -1.000000, 0.000000, 0.000000)
                r1_0.xy = r1_0.xy * float2(2.0f, 2.0f) + float2(-1.0f, -1.0f);
                //    5: dp2 r1.w, r1.xyxx, r1.xyxx
                r1_0.w = dot(r1_0.xy, r1_0.xy);
                //    6: min r1.w, r1.w, l(1.000000)
                r1_0.w = min(r1_0.w, 1.0f);
                //    7: add r1.w, -r1.w, l(1.000000)
                r1_0.w = -r1_0.w + 1.0f;
                //    8: sqrt r1.z, r1.w
                r1_0.z = sqrt(r1_0.w);
                //    9: mad r1.xyz, r1.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), l(0.500000, 0.500000, 0.500000, 0.000000)
                r1_0.xyz = r1_0.xyz * float3(0.5f, 0.5f, 0.5f) + float3(0.5f, 0.5f, 0.5f);
                //   10: mov r1.w, l(1.000000)
                r1_0.w = 1.0f;
                //   11: movc r0.xyzw, cb0[2].wwww, r1.zxwy, r0.zxwy
                r0_2 = asuint(_IsNormalMap) ? r1_0 : r0_1;
                //   12: exp r1.x, cb0[3].x
                r1_1.x = exp2(_Exposure);
                //   13: mul r1.xyz, r0.ywxy, r1.xxxx
                r1_1.xyz = r1_1.x * r0_2.xyz;
                //   14: max r2.xyz, r1.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
                r2_0.xyz = max(r1_1.xyz, float3(0.0f, 0.0f, 0.0f));
                //   15: log r2.xyz, r2.xyzx
                r2_0.xyz = log2(r2_0.xyz);
                //   16: mul r2.xyz, r2.xyzx, l(0.416667, 0.416667, 0.416667, 0.000000)
                r2_0.xyz = r2_0.xyz * float3(0.416666657f, 0.416666657f, 0.416666657f);
                //   17: exp r2.xyz, r2.xyzx
                r2_0.xyz = exp2(r2_0.xyz);
                //   18: mad r2.xyz, r2.xyzx, l(1.055000, 1.055000, 1.055000, 0.000000), l(-0.055000, -0.055000, -0.055000, 0.000000)
                r2_0.xyz = r2_0.xyz * float3(1.05499995f, 1.05499995f, 1.05499995f) + float3(-0.0549999997f, -0.0549999997f, -0.0549999997f);
                //   19: max r2.xyz, r2.xyzx, l(0.000000, 0.000000, 0.000000, 0.000000)
                r2_0.xyz = max(r2_0.xyz, float3(0.0f, 0.0f, 0.0f));
                //   20: movc r0.xyw, cb0[3].yyyy, r2.zxzy, r1.zxzy
                r0_2.xyz = asuint(_ToSRGB) ? r2_0.xyz : r1_1.xyz;
                //   21: ieq r1.xyzw, cb0[2].zzzz, l(1, 2, 4, 8)
                    r1_2.x = asfloat((_ColorMaskBits == 1) ? 0xFFFFFFFFu : 0u);
                r1_2.y = asfloat((_ColorMaskBits == 2) ? 0xFFFFFFFFu : 0u);
                r1_2.z = asfloat((_ColorMaskBits == 4) ? 0xFFFFFFFFu : 0u);
                r1_2.w = asfloat((_ColorMaskBits == 8) ? 0xFFFFFFFFu : 0u);
                //   22: movc r0.xzw, r1.xxxx, l(0,0,1.000000,0), r0.xxzw
                r0_2.yzw = asuint(r1_2.x) ? float3(0.0f, 0.0f, 1.0f) : r0_2.yzw;
                //   23: movc r0.xyz, r1.yyyy, l(0,1.000000,0,0), r0.yzxy
                r0_2.xzw = asuint(r1_2.y) ? float3(0.0f, 0.0f, 1.0f) : r0_2.xzw;
                //   24: movc r2.xyz, r1.zzzz, l(0,0,1.000000,0), r0.xwyx
                r2_1.xyz = asuint(r1_2.z) ? float3(0.0f, 0.0f, 1.0f) : r0_2.xyw;
                //   25: mov r0.xyw, r2.xyxz
                r0_2.xyw = r2_1.xyz;
                //   26: mov r2.w, l(1.000000)
                r2_1.w = 1.0f;
                //   27: movc o0.xyzw, r1.wwww, r2.zzzw, r0.xyzw
                o0 = asuint(r1_2.w) ? r2_1.zzzw : r0_2;
                //   28: ret
                return o0;
                return o0;
            }

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

