// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "Unlit/Transparent"
{
    Properties
    {
        _MainTex ("Base (RGB) Trans (A)", 2D) = "white" {}
    }

    SubShader
    {
        Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
        LOD 100
        Pass
        {
            Tags { "IGNOREPROJECTOR"="true" "QUEUE"="Transparent" "RenderType"="Transparent" }
            ZWrite Off
            Blend SrcAlpha OneMinusSrcAlpha
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _MainTex_ST;
            
            cbuffer UnityPerDraw : register(b1) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b2) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _MainTex_ST;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float2 o1 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb1[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb1[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb1[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mad o1.xy, v1.xyxx, cb0[2].xyxx, cb0[2].zwzz
                o1.xy = v1.xy * _MainTex_ST.xy + _MainTex_ST.zw;
                //    9: ret
                output.o0 = o0;
                output.o1 = o1.xy;
                return output;
                output.o0 = o0;
                output.o1 = o1.xy;
                return output;
            }

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            Texture2D _MainTex : register(t0);
            SamplerState sampler_MainTex : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float2 v1 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                float4 o0 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample o0.xyzw, v1.xyxx, t0.xyzw, s0
                o0 = _MainTex.Sample(sampler_MainTex, v1.xy);
                //    1: ret
                return o0;
                return o0;
            }

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

