// SPDX-License-Identifier: GPL-3.0-only
// Authored evaluation input only. Do not dispatch as part of capture.
#pragma kernel FillUint4
#pragma kernel CopyUint4
#pragma kernel AddUint4
#pragma only_renderers d3d11
#pragma multi_compile __ OFFSET_TEXELS

Texture2D<uint4> _Source;
RWTexture2D<uint4> _Destination;

#if defined(OFFSET_TEXELS)
    #define GROUP_WIDTH 4
#else
    #define GROUP_WIDTH 8
#endif

[numthreads(GROUP_WIDTH, GROUP_WIDTH, 1)]
void FillUint4(uint3 dispatchId : SV_DispatchThreadID)
{
    uint2 coordinates = dispatchId.xy;
    #if defined(OFFSET_TEXELS)
        coordinates += uint2(1u, 2u);
    #endif
    _Destination[coordinates] = uint4(11u, 22u, 33u, 44u);
}

[numthreads(GROUP_WIDTH, GROUP_WIDTH, 1)]
void CopyUint4(uint3 dispatchId : SV_DispatchThreadID)
{
    uint2 coordinates = dispatchId.xy;
    #if defined(OFFSET_TEXELS)
        coordinates += uint2(1u, 2u);
    #endif
    _Destination[coordinates] = _Source.Load(int3(coordinates, 0));
}

[numthreads(GROUP_WIDTH, GROUP_WIDTH, 1)]
void AddUint4(uint3 dispatchId : SV_DispatchThreadID)
{
    uint2 coordinates = dispatchId.xy;
    #if defined(OFFSET_TEXELS)
        coordinates += uint2(1u, 2u);
    #endif
    _Destination[coordinates] = _Source.Load(int3(coordinates, 0)) + uint4(1u, 2u, 3u, 4u);
}
