// SPDX-License-Identifier: GPL-3.0-only
#ifndef SHADERLAB_SOURCE_QUALITY_H
#define SHADERLAB_SOURCE_QUALITY_H

#include "io/shader_object.h"
#include "translation/shaderlab_emitter.h"
#include "translation/shaderlab_structural_certificate.h"

/* All request storage must remain valid and immutable during either call.
 * This inventory observes source generated by the ordinary high-level route.
 * It is independent of compiler equality, generated-domain and native gates.
 * Its initial scope is one ordinary V/F pass with scalar/vector/texture properties and a
 * bounded keyword domain. External include semantics remain unavailable. */
typedef enum {
    SHADERLAB_SOURCE_SYNTAX_HEADER = 0,
    SHADERLAB_SOURCE_SYNTAX_PROPERTIES_BEGIN,
    SHADERLAB_SOURCE_SYNTAX_PROPERTY,
    SHADERLAB_SOURCE_SYNTAX_PROPERTIES_END,
    SHADERLAB_SOURCE_SYNTAX_SUBSHADER_BEGIN,
    SHADERLAB_SOURCE_SYNTAX_SUBSHADER_TAGS,
    SHADERLAB_SOURCE_SYNTAX_SUBSHADER_LOD,
    SHADERLAB_SOURCE_SYNTAX_PASS_BEGIN,
    SHADERLAB_SOURCE_SYNTAX_PASS_NAME,
    SHADERLAB_SOURCE_SYNTAX_PASS_TAGS,
    SHADERLAB_SOURCE_SYNTAX_PASS_LOD,
    SHADERLAB_SOURCE_SYNTAX_RENDER_STATE,
    SHADERLAB_SOURCE_SYNTAX_PROGRAM_BEGIN,
    SHADERLAB_SOURCE_SYNTAX_ENTRY_PRAGMAS,
    SHADERLAB_SOURCE_SYNTAX_TARGET_PRAGMAS,
    SHADERLAB_SOURCE_SYNTAX_KEYWORD_PRAGMAS,
    SHADERLAB_SOURCE_SYNTAX_INCLUDE_POLICY,
    SHADERLAB_SOURCE_SYNTAX_STAGE_GUARD,
    SHADERLAB_SOURCE_SYNTAX_ROUTING,
    SHADERLAB_SOURCE_SYNTAX_LINKED_ENTRY,
    SHADERLAB_SOURCE_SYNTAX_PROGRAM_END,
    SHADERLAB_SOURCE_SYNTAX_PASS_END,
    SHADERLAB_SOURCE_SYNTAX_SUBSHADER_END,
    SHADERLAB_SOURCE_SYNTAX_TRAILER,
    SHADERLAB_SOURCE_SYNTAX_SHADER_END
} ShaderLabSourceSyntaxKind;

typedef struct {
    ShaderLabSourceSyntaxKind kind;
    size_t source_begin;
    size_t source_end;
    uint8_t source_digest[COMMON_SHA256_DIGEST_SIZE];
    int property_index;
    int subshader_index;
    int pass_index;
    int stage_index;
    /* SIZE_MAX for wrapper/routing syntax; otherwise indexes actual stage
     * source records. The linked entry retains its own AST-derived quality. */
    size_t entry_record_index;
} ShaderLabSourceSyntaxReceipt;

enum {
    SHADERLAB_SOURCE_GAP_EXTERNAL_INCLUDE = 1u << 0,
    SHADERLAB_SOURCE_GAP_DEPENDENCY_INVENTORY = 1u << 1,
    SHADERLAB_SOURCE_GAP_SCHEMA_AUTHORITY = 1u << 2,
    SHADERLAB_SOURCE_GAP_STAGE_COVERAGE = 1u << 3
};

typedef struct {
    HLSLSourceQualityClass classification;
    uint32_t reasons;
    uint32_t gaps;
    bool wrapper_complete;
    size_t wrapper_receipt_count;
    size_t linked_entry_count;
    size_t stage_class_counts[5];
    /* Lower bounds copied from independently observed linked stage units.
     * They do not account for uninspected includes or dependency source. No
     * stage expression observation is converted to an emission fact. */
    size_t observed_stage_residual_total;
    size_t observed_stage_unknown_provenance;
    size_t observed_stage_incomplete_units;
    /* Actual emitted literal roots only. Native implicit roots and the
     * transitive closure remain unenumerated, behind the include gap. */
    size_t required_external_include_root_count;
} ShaderLabSourceQualityResult;

typedef struct {
    ShaderLabSourceSyntaxReceipt *receipts;
    size_t receipt_count;
    size_t receipt_capacity;
    ShaderLabExpressionSourceMap entries;
    size_t source_size;
    uint8_t source_digest[COMMON_SHA256_DIGEST_SIZE];
    /* Scoped selected-model identity, including generated wrapper/routing,
     * ordered raw keyword metadata and each linked source/target coordinate.
     * It is not a wire-object digest or authentication of caller metadata. */
    uint8_t modeled_input_digest[COMMON_SHA256_DIGEST_SIZE];
    bool complete;
    ShaderLabSourceQualityResult quality;
    /* Kept separate: this certificate never supplies include/stage quality. */
    bool has_structural_authority;
    ShaderLabStructuralDiagnostic structure;
} ShaderLabSourceQualityInventory;

typedef bool (*ShaderLabSourceSyntaxObserver)(
    void *context, const ShaderLabSourceSyntaxReceipt *receipt);

typedef struct {
    const SerializedShader *shader;
    const ShaderBlobArchive *archive;
    /* Optional decoded schema authority. When supplied, shader must be
     * exactly &object->shader. Without it the schema gap remains explicit. */
    const ShaderObject *object;
    ShaderLabSourceSyntaxObserver observer;
    void *observer_context;
} ShaderLabSourceQualityRequest;

typedef enum {
    SHADERLAB_SOURCE_QUALITY_OK = 0,
    SHADERLAB_SOURCE_QUALITY_INVALID_ARGUMENT,
    SHADERLAB_SOURCE_QUALITY_SCOPE_UNAVAILABLE,
    SHADERLAB_SOURCE_QUALITY_STRUCTURE_FAILED,
    SHADERLAB_SOURCE_QUALITY_EMISSION_FAILED,
    SHADERLAB_SOURCE_QUALITY_INVENTORY_MISMATCH,
    SHADERLAB_SOURCE_QUALITY_OBSERVER_REJECTED,
    SHADERLAB_SOURCE_QUALITY_ALLOCATION_FAILED
} ShaderLabSourceQualityStatus;

typedef struct {
    ShaderLabSourceQualityStatus status;
    ShaderLabCandidateDiagnostic emission;
    ShaderLabStructuralDiagnostic structure;
} ShaderLabSourceQualityDiagnostic;

/* Initialize with {0}. Disposal resets owned receipts and linked stage map. */
void shaderlab_source_quality_inventory_dispose(ShaderLabSourceQualityInventory *inventory);

/* Requires an empty initialized output. Failure preserves output and an
 * initialized destination. Success emits exactly the existing high-level
 * candidate bytes and retains MIXED while external scope is uninspected. */
ShaderLabSourceQualityStatus shaderlab_source_quality_emit(
    const ShaderLabSourceQualityRequest *request, StringBuilder *source,
    ShaderLabSourceQualityInventory *destination,
    ShaderLabSourceQualityDiagnostic *diagnostic);

/* Reconstructs canonical typed receipts from the same current model/archive
 * and checks every byte range, linked owner, outcome and hash independently.
 * Source, receipt or model mutation cannot reuse old coverage. No compiler or
 * runtime service is called. Failure leaves the result unchanged. */
ShaderLabSourceQualityStatus shaderlab_source_quality_inventory_analyze(
    const ShaderLabSourceQualityRequest *request, const StringBuilder *source,
    const ShaderLabSourceQualityInventory *inventory,
    ShaderLabSourceQualityResult *result,
    ShaderLabSourceQualityDiagnostic *diagnostic);

#endif
