// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "Hidden/ShowShadowCascadeSplits"
{
    Properties
    {
    }

    SubShader
    {
        Pass
        {
            Cull Off
            ZWrite Off
            ZTest Always
            Blend SrcAlpha OneMinusSrcAlpha
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 3.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            #if defined(SHADOWS_SPLIT_SPHERES)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 ComputeNonStereoScreenPos(float4 pos, float proj_param) {
                float4 o = pos * 0.5f;
                o.xy = float2(o.x, o.y * proj_param) + o.w;
                o.zw = pos.zw;
                return o;
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : TEXCOORD0;
                float3 o2 : TEXCOORD1;
                float3 o3 : TEXCOORD2;
                float3 o4 : TEXCOORD3;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                v2.xyz = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 o3 = (float4)0;
                float4 o4 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o0.xyzw, r0.xyzw
                o0 = r0_4;
                // Optimized ComputeScreenPos sequence
            o1.zw = ComputeNonStereoScreenPos(r0_4, _ProjectionParams.x).xy;
                r0_4.y = r0_4.y * _ProjectionParams.x;
                //   10: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
                //   11: mul r0.yzw, r0.yyyy, cb1[11].xxyz
                r0_4.yzw = transpose(unity_CameraInvProjection)[1].xyz * r0_4.y;
                //   12: mad r0.xyz, cb1[10].xyzx, r0.xxxx, r0.yzwy
                r0_4.xyz = transpose(unity_CameraInvProjection)[0].xyz * r0_4.x + r0_4.yzw;
                //   13: add o1.zw, r1.zzzz, r1.xxxw
                //   14: mov o1.xy, v1.xyxx
                o1.xy = v1.xy;
                //   15: mov o2.xyz, v2.xyzx
                o2.xyz = v2.xyz;
                //   16: add r1.xyz, r0.xyzx, -cb1[12].xyzx
                r1_4.xyz = r0_4.xyz + -transpose(unity_CameraInvProjection)[2].xyz;
                //   17: add r0.xyz, r0.xyzx, cb1[12].xyzx
                r0_4.xyz = r0_4.xyz + transpose(unity_CameraInvProjection)[2].xyz;
                //   18: add r0.xyz, r0.xyzx, cb1[13].xyzx
                r0_4.xyz = transpose(unity_CameraInvProjection)[3].xyz + r0_4.xyz;
                //   19: add r1.xyz, r1.xyzx, cb1[13].xyzx
                r1_4.xyz = r1_4.xyz + transpose(unity_CameraInvProjection)[3].xyz;
                //   20: mov r1.w, -r1.z
                r1_4.w = -r1_4.z;
                //   21: mov o3.xyz, r1.xywx
                o3.xyz = r1_4.xyw;
                //   22: mov r0.w, -r0.z
                r0_4.w = -r0_4.z;
                //   23: mov o4.xyz, r0.xywx
                o4.xyz = r0_4.xyw;
                //   24: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
            }
            #elif defined(SHADOWS_SINGLE_CASCADE)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 ComputeNonStereoScreenPos(float4 pos, float proj_param) {
                float4 o = pos * 0.5f;
                o.xy = float2(o.x, o.y * proj_param) + o.w;
                o.zw = pos.zw;
                return o;
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : TEXCOORD0;
                float3 o2 : TEXCOORD1;
                float3 o3 : TEXCOORD2;
                float3 o4 : TEXCOORD3;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                v2.xyz = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 o3 = (float4)0;
                float4 o4 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o0.xyzw, r0.xyzw
                o0 = r0_4;
                // Optimized ComputeScreenPos sequence
            o1.zw = ComputeNonStereoScreenPos(r0_4, _ProjectionParams.x).xy;
                r0_4.y = r0_4.y * _ProjectionParams.x;
                //   10: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
                //   11: mul r0.yzw, r0.yyyy, cb1[11].xxyz
                r0_4.yzw = transpose(unity_CameraInvProjection)[1].xyz * r0_4.y;
                //   12: mad r0.xyz, cb1[10].xyzx, r0.xxxx, r0.yzwy
                r0_4.xyz = transpose(unity_CameraInvProjection)[0].xyz * r0_4.x + r0_4.yzw;
                //   13: add o1.zw, r1.zzzz, r1.xxxw
                //   14: mov o1.xy, v1.xyxx
                o1.xy = v1.xy;
                //   15: mov o2.xyz, v2.xyzx
                o2.xyz = v2.xyz;
                //   16: add r1.xyz, r0.xyzx, -cb1[12].xyzx
                r1_4.xyz = r0_4.xyz + -transpose(unity_CameraInvProjection)[2].xyz;
                //   17: add r0.xyz, r0.xyzx, cb1[12].xyzx
                r0_4.xyz = r0_4.xyz + transpose(unity_CameraInvProjection)[2].xyz;
                //   18: add r0.xyz, r0.xyzx, cb1[13].xyzx
                r0_4.xyz = transpose(unity_CameraInvProjection)[3].xyz + r0_4.xyz;
                //   19: add r1.xyz, r1.xyzx, cb1[13].xyzx
                r1_4.xyz = r1_4.xyz + transpose(unity_CameraInvProjection)[3].xyz;
                //   20: mov r1.w, -r1.z
                r1_4.w = -r1_4.z;
                //   21: mov o3.xyz, r1.xywx
                o3.xyz = r1_4.xyw;
                //   22: mov r0.w, -r0.z
                r0_4.w = -r0_4.z;
                //   23: mov o4.xyz, r0.xywx
                o4.xyz = r0_4.xyw;
                //   24: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
            }
            #elif defined(SHADOWS_SPLIT_SPHERES) && defined(SHADOWS_SINGLE_CASCADE)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 ComputeNonStereoScreenPos(float4 pos, float proj_param) {
                float4 o = pos * 0.5f;
                o.xy = float2(o.x, o.y * proj_param) + o.w;
                o.zw = pos.zw;
                return o;
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : TEXCOORD0;
                float3 o2 : TEXCOORD1;
                float3 o3 : TEXCOORD2;
                float3 o4 : TEXCOORD3;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                v2.xyz = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 o3 = (float4)0;
                float4 o4 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o0.xyzw, r0.xyzw
                o0 = r0_4;
                // Optimized ComputeScreenPos sequence
            o1.zw = ComputeNonStereoScreenPos(r0_4, _ProjectionParams.x).xy;
                r0_4.y = r0_4.y * _ProjectionParams.x;
                //   10: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
                //   11: mul r0.yzw, r0.yyyy, cb1[11].xxyz
                r0_4.yzw = transpose(unity_CameraInvProjection)[1].xyz * r0_4.y;
                //   12: mad r0.xyz, cb1[10].xyzx, r0.xxxx, r0.yzwy
                r0_4.xyz = transpose(unity_CameraInvProjection)[0].xyz * r0_4.x + r0_4.yzw;
                //   13: add o1.zw, r1.zzzz, r1.xxxw
                //   14: mov o1.xy, v1.xyxx
                o1.xy = v1.xy;
                //   15: mov o2.xyz, v2.xyzx
                o2.xyz = v2.xyz;
                //   16: add r1.xyz, r0.xyzx, -cb1[12].xyzx
                r1_4.xyz = r0_4.xyz + -transpose(unity_CameraInvProjection)[2].xyz;
                //   17: add r0.xyz, r0.xyzx, cb1[12].xyzx
                r0_4.xyz = r0_4.xyz + transpose(unity_CameraInvProjection)[2].xyz;
                //   18: add r0.xyz, r0.xyzx, cb1[13].xyzx
                r0_4.xyz = transpose(unity_CameraInvProjection)[3].xyz + r0_4.xyz;
                //   19: add r1.xyz, r1.xyzx, cb1[13].xyzx
                r1_4.xyz = r1_4.xyz + transpose(unity_CameraInvProjection)[3].xyz;
                //   20: mov r1.w, -r1.z
                r1_4.w = -r1_4.z;
                //   21: mov o3.xyz, r1.xywx
                o3.xyz = r1_4.xyw;
                //   22: mov r0.w, -r0.z
                r0_4.w = -r0_4.z;
                //   23: mov o4.xyz, r0.xywx
                o4.xyz = r0_4.xyw;
                //   24: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
            }
            #else
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 ComputeNonStereoScreenPos(float4 pos, float proj_param) {
                float4 o = pos * 0.5f;
                o.xy = float2(o.x, o.y * proj_param) + o.w;
                o.zw = pos.zw;
                return o;
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float2 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : TEXCOORD0;
                float3 o2 : TEXCOORD1;
                float3 o3 : TEXCOORD2;
                float3 o4 : TEXCOORD3;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                v2.xyz = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 o3 = (float4)0;
                float4 o4 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb2[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb2[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o0.xyzw, r0.xyzw
                o0 = r0_4;
                // Optimized ComputeScreenPos sequence
            o1.zw = ComputeNonStereoScreenPos(r0_4, _ProjectionParams.x).xy;
                r0_4.y = r0_4.y * _ProjectionParams.x;
                //   10: mul r1.xzw, r0.xxwy, l(0.500000, 0.000000, 0.500000, 0.500000)
                //   11: mul r0.yzw, r0.yyyy, cb1[11].xxyz
                r0_4.yzw = transpose(unity_CameraInvProjection)[1].xyz * r0_4.y;
                //   12: mad r0.xyz, cb1[10].xyzx, r0.xxxx, r0.yzwy
                r0_4.xyz = transpose(unity_CameraInvProjection)[0].xyz * r0_4.x + r0_4.yzw;
                //   13: add o1.zw, r1.zzzz, r1.xxxw
                //   14: mov o1.xy, v1.xyxx
                o1.xy = v1.xy;
                //   15: mov o2.xyz, v2.xyzx
                o2.xyz = v2.xyz;
                //   16: add r1.xyz, r0.xyzx, -cb1[12].xyzx
                r1_4.xyz = r0_4.xyz + -transpose(unity_CameraInvProjection)[2].xyz;
                //   17: add r0.xyz, r0.xyzx, cb1[12].xyzx
                r0_4.xyz = r0_4.xyz + transpose(unity_CameraInvProjection)[2].xyz;
                //   18: add r0.xyz, r0.xyzx, cb1[13].xyzx
                r0_4.xyz = transpose(unity_CameraInvProjection)[3].xyz + r0_4.xyz;
                //   19: add r1.xyz, r1.xyzx, cb1[13].xyzx
                r1_4.xyz = r1_4.xyz + transpose(unity_CameraInvProjection)[3].xyz;
                //   20: mov r1.w, -r1.z
                r1_4.w = -r1_4.z;
                //   21: mov o3.xyz, r1.xywx
                o3.xyz = r1_4.xyw;
                //   22: mov r0.w, -r0.z
                r0_4.w = -r0_4.z;
                //   23: mov o4.xyz, r0.xywx
                o4.xyz = r0_4.xyw;
                //   24: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xyz;
                output.o3 = o3.xyz;
                output.o4 = o4.xyz;
                return output;
            }
            #endif

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            #if defined(SHADOWS_SPLIT_SPHERES)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            static const float4 unk0_arr[] = {
                float4(0.500000, 0.500000, 0.700000, 0.500000),
                float4(0.500000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.500000, 0.500000, 0.500000)
            };
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
                float4 _ZBufferParams;
                float4 unity_OrthoParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
                float4x4 unity_WorldToCamera;
                float4x4 unity_CameraToWorld;
            };
            
            cbuffer UnityShadows : register(b2) {
                float4 unity_ShadowSplitSpheres[4];
                float4 unity_ShadowSplitSqRadii;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    case 7: return _ZBufferParams;
                    case 8: return unity_OrthoParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    case 14: return unity_WorldToCamera[0];
                    case 15: return unity_WorldToCamera[1];
                    case 16: return unity_WorldToCamera[2];
                    case 17: return unity_WorldToCamera[3];
                    case 18: return unity_CameraToWorld[0];
                    case 19: return unity_CameraToWorld[1];
                    case 20: return unity_CameraToWorld[2];
                    case 21: return unity_CameraToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ShadowSplitSpheres[0];
                    case 1: return unity_ShadowSplitSpheres[1];
                    case 2: return unity_ShadowSplitSpheres[2];
                    case 3: return unity_ShadowSplitSpheres[3];
                    case 4: return unity_ShadowSplitSqRadii;
                    default: return (float4)0;
                }
            }
            
            Texture2D _CameraDepthTexture : register(t0);
            SamplerState sampler_CameraDepthTexture : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
                float3 v3 : TEXCOORD2;
                float3 v4 : TEXCOORD3;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                float4 v3 = (float4)0;
                float4 v4 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xyz = input.v2;
                v3.xyz = input.v3;
                v4.xyz = input.v4;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r2 = (float4)0;
                float4 r3 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
                r0_0 = _CameraDepthTexture.Sample(sampler_CameraDepthTexture, v1.xy);
                //    1: mad r0.y, cb0[7].x, r0.x, cb0[7].y
                r0_0.y = _ZBufferParams.x * r0_0.x + _ZBufferParams.y;
                //    2: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
                r0_0.y = 1.0f / r0_0.y;
                //    3: add r0.x, -r0.x, l(1.000000)
                r0_0.x = -r0_0.x + 1.0f;
                //    4: add r0.z, -r0.y, r0.x
                r0_0.z = mad(-r0_0.y, 1.0, r0_0.x);
                //    5: mad r0.y, cb0[8].w, r0.z, r0.y
                r0_0.y = unity_OrthoParams.w * r0_0.z + r0_0.y;
                //    6: mul r1.xyz, r0.yyyy, v2.xyzx
                r1_0.xyz = v2.xyz * r0_0.y;
                //    7: add r2.xyz, -v3.xyzx, v4.xyzx
                r2.xyz = -v3.xyz + v4.xyz;
                //    8: mad r0.xzw, r0.xxxx, r2.xxyz, v3.xxyz
                u_xlat_temp_x = r0_0.x * r2.x + v3.x;
                u_xlat_temp_z = r0_0.x * r2.y + v3.y;
                u_xlat_temp_w = r0_0.x * r2.z + v3.z;
                r0_0.x = u_xlat_temp_x;
                r0_0.z = u_xlat_temp_z;
                r0_0.w = u_xlat_temp_w;
                //    9: mad r0.xyz, -v2.xyzx, r0.yyyy, r0.xzwx
                r0_0.xyz = r0_0.xzw - v2.xyz * r0_0.y;
                //   10: mad r0.xyz, cb0[8].wwww, r0.xyzx, r1.xyzx
                r0_0.xyz = unity_OrthoParams.w * r0_0.xyz + r1_0.xyz;
                //   11: mul r1.xyz, r0.yyyy, cb1[19].xyzx
                r1_0.xyz = transpose(unity_CameraToWorld)[1].xyz * r0_0.y;
                //   12: mad r0.xyw, cb1[18].xyxz, r0.xxxx, r1.xyxz
                u_xlat_temp_x = transpose(unity_CameraToWorld)[0].x * r0_0.x + r1_0.x;
                u_xlat_temp_y = transpose(unity_CameraToWorld)[0].y * r0_0.x + r1_0.y;
                u_xlat_temp_w = transpose(unity_CameraToWorld)[0].z * r0_0.x + r1_0.z;
                r0_0.x = u_xlat_temp_x;
                r0_0.y = u_xlat_temp_y;
                r0_0.w = u_xlat_temp_w;
                //   13: mad r0.xyz, cb1[20].xyzx, r0.zzzz, r0.xywx
                r0_0.xyz = transpose(unity_CameraToWorld)[2].xyz * r0_0.z + r0_0.xyw;
                //   14: add r0.xyz, r0.xyzx, cb1[21].xyzx
                r0_0.xyz = transpose(unity_CameraToWorld)[3].xyz + r0_0.xyz;
                //   15: add r1.xyz, r0.xyzx, -cb2[0].xyzx
                r1_0.xyz = -unity_ShadowSplitSpheres[0].xyz + r0_0.xyz;
                //   16: add r2.xyz, r0.xyzx, -cb2[1].xyzx
                r2.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[1].xyz;
                //   17: add r3.xyz, r0.xyzx, -cb2[2].xyzx
                r3.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[2].xyz;
                //   18: add r0.xyz, r0.xyzx, -cb2[3].xyzx
                r0_0.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[3].xyz;
                //   19: dp3 r1.x, r1.xyzx, r1.xyzx
                r1_0.x = dot(r1_0.xyz, r1_0.xyz);
                //   20: dp3 r1.y, r2.xyzx, r2.xyzx
                r1_0.y = dot(r2.xyz, r2.xyz);
                //   21: dp3 r1.z, r3.xyzx, r3.xyzx
                r1_0.z = dot(r3.xyz, r3.xyz);
                //   22: dp3 r1.w, r0.xyzx, r0.xyzx
                r1_0.w = dot(r0_0.xyz, r0_0.xyz);
                //   23: lt r0.xyzw, r1.xyzw, cb2[4].xyzw
                r0_1 = asfloat((r1_0 < unity_ShadowSplitSqRadii) ? 0xFFFFFFFFu : 0u);
                //   24: and r1.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r1_1 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r0_1));
                //   25: movc r0.xyz, r0.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
                r0_1.xyz = asuint(r0_1.xyz) ? float3(-1.0f, -1.0f, -1.0f) : float3(-0.0f, -0.0f, -0.0f);
                //   26: add r0.xyz, r0.xyzx, r1.yzwy
                r0_1.xyz = r1_1.yzw + r0_1.xyz;
                //   27: max r1.yzw, r0.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
                r1_1.yzw = max(r0_1.xyz, float3(0.0f, 0.0f, 0.0f));
                //   28: dp4 r0.x, r1.xyzw, l(1.000000, 2.000000, 3.000000, 4.000000)
                r0_1.x = dot(r1_1, float4(1.0f, 2.0f, 3.0f, 4.0f));
                //   29: add r0.x, r0.x, l(-1.000000)
                r0_1.x = r0_1.x + -1.0f;
                //   30: ge r0.y, r0.x, l(0.000000)
                r0_1.y = asfloat((r0_1.x >= 0.0f) ? 0xFFFFFFFFu : 0u);
                //   31: if_nz r0.y
                [branch] if (asuint(r0_1.y)) {
                    //   32: ftou r0.x, r0.x
                    r0_1.x = asfloat((uint)(r0_1.x));
                    //   33: mov o0.xyz, icb[r0.x + 0].xyzx
                    o0.xyz = unk0_arr[asint(asint(r0_1.x)) + 0].xyz;
                    //   34: mov o0.w, l(0.500000)
                    o0.w = 0.5f;
                //   35: else
                } else {
                    //   36: mov o0.xyzw, l(1.000000,1.000000,1.000000,0)
                    o0 = float4(1.0f, 1.0f, 1.0f, 0.0f);
                //   37: endif
                }
                //   38: ret
                return o0;
                return o0;
            }
            #elif defined(SHADOWS_SINGLE_CASCADE)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            static const float4 unk0_arr[] = {
                float4(0.500000, 0.500000, 0.700000, 0.500000),
                float4(0.500000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.500000, 0.500000, 0.500000)
            };
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
                float4 _ZBufferParams;
                float4 unity_OrthoParams;
            };
            
            cbuffer UnityShadows : register(b1) {
                float4 unity_ShadowSplitSpheres[4];
                float4 unity_ShadowSplitSqRadii;
                float4 unity_LightShadowBias;
                float4 _LightSplitsNear;
                float4 _LightSplitsFar;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    case 7: return _ZBufferParams;
                    case 8: return unity_OrthoParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ShadowSplitSpheres[0];
                    case 1: return unity_ShadowSplitSpheres[1];
                    case 2: return unity_ShadowSplitSpheres[2];
                    case 3: return unity_ShadowSplitSpheres[3];
                    case 4: return unity_ShadowSplitSqRadii;
                    case 5: return unity_LightShadowBias;
                    case 6: return _LightSplitsNear;
                    case 7: return _LightSplitsFar;
                    default: return (float4)0;
                }
            }
            
            Texture2D _CameraDepthTexture : register(t0);
            SamplerState sampler_CameraDepthTexture : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
                float3 v3 : TEXCOORD2;
                float3 v4 : TEXCOORD3;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                float4 v3 = (float4)0;
                float4 v4 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xyz = input.v2;
                v3.xyz = input.v3;
                v4.xyz = input.v4;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
                r0_0 = _CameraDepthTexture.Sample(sampler_CameraDepthTexture, v1.xy);
                //    1: mad r0.y, cb0[7].x, r0.x, cb0[7].y
                r0_0.y = _ZBufferParams.x * r0_0.x + _ZBufferParams.y;
                //    2: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
                r0_0.y = 1.0f / r0_0.y;
                //    3: add r0.x, -r0.x, l(1.000000)
                r0_0.x = -r0_0.x + 1.0f;
                //    4: add r0.z, -r0.y, r0.x
                r0_0.z = mad(-r0_0.y, 1.0, r0_0.x);
                //    5: mad r0.y, cb0[8].w, r0.z, r0.y
                r0_0.y = unity_OrthoParams.w * r0_0.z + r0_0.y;
                //    6: mul r0.z, r0.y, v2.z
                r0_0.z = v2.z * r0_0.y;
                //    7: add r0.w, -v3.z, v4.z
                r0_0.w = -v3.z + v4.z;
                //    8: mad r0.x, r0.x, r0.w, v3.z
                r0_0.x = r0_0.x * r0_0.w + v3.z;
                //    9: mad r0.x, -v2.z, r0.y, r0.x
                r0_0.x = r0_0.x - v2.z * r0_0.y;
                //   10: mad r0.x, cb0[8].w, r0.x, r0.z
                r0_0.x = unity_OrthoParams.w * r0_0.x + r0_0.z;
                //   11: ge r1.xyzw, r0.xxxx, cb1[6].xyzw
                r1_0 = asfloat((r0_0.x >= _LightSplitsNear) ? 0xFFFFFFFFu : 0u);
                //   12: and r1.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r1_1 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r1_0));
                //   13: lt r0.xyzw, r0.xxxx, cb1[7].xyzw
                r0_1 = asfloat((r0_0.x < _LightSplitsFar) ? 0xFFFFFFFFu : 0u);
                //   14: and r0.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r0_2 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r0_1));
                //   15: mul r0.xyzw, r0.xyzw, r1.xyzw
                r0_3 = r1_1 * r0_2;
                //   16: dp4 r0.x, r0.xyzw, l(1.000000, 2.000000, 3.000000, 4.000000)
                r0_3.x = dot(r0_3, float4(1.0f, 2.0f, 3.0f, 4.0f));
                //   17: add r0.x, r0.x, l(-1.000000)
                r0_3.x = r0_3.x + -1.0f;
                //   18: ge r0.y, r0.x, l(0.000000)
                r0_3.y = asfloat((r0_3.x >= 0.0f) ? 0xFFFFFFFFu : 0u);
                //   19: if_nz r0.y
                [branch] if (asuint(r0_3.y)) {
                    //   20: ftou r0.x, r0.x
                    r0_3.x = asfloat((uint)(r0_3.x));
                    //   21: mov o0.xyz, icb[r0.x + 0].xyzx
                    o0.xyz = unk0_arr[asint(asint(r0_3.x)) + 0].xyz;
                    //   22: mov o0.w, l(0.500000)
                    o0.w = 0.5f;
                //   23: else
                } else {
                    //   24: mov o0.xyzw, l(1.000000,1.000000,1.000000,0)
                    o0 = float4(1.0f, 1.0f, 1.0f, 0.0f);
                //   25: endif
                }
                //   26: ret
                return o0;
                return o0;
            }
            #elif defined(SHADOWS_SPLIT_SPHERES) && defined(SHADOWS_SINGLE_CASCADE)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            static const float4 unk0_arr[] = {
                float4(0.500000, 0.500000, 0.700000, 0.500000),
                float4(0.500000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.500000, 0.500000, 0.500000)
            };
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
                float4 _ZBufferParams;
                float4 unity_OrthoParams;
            };
            
            cbuffer UnityPerCameraRare : register(b1) {
                float4 unity_CameraWorldClipPlanes[6];
                float4x4 unity_CameraProjection;
                float4x4 unity_CameraInvProjection;
                float4x4 unity_WorldToCamera;
                float4x4 unity_CameraToWorld;
            };
            
            cbuffer UnityShadows : register(b2) {
                float4 unity_ShadowSplitSpheres[4];
                float4 unity_ShadowSplitSqRadii;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    case 7: return _ZBufferParams;
                    case 8: return unity_OrthoParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_CameraWorldClipPlanes[0];
                    case 1: return unity_CameraWorldClipPlanes[1];
                    case 2: return unity_CameraWorldClipPlanes[2];
                    case 3: return unity_CameraWorldClipPlanes[3];
                    case 4: return unity_CameraWorldClipPlanes[4];
                    case 5: return unity_CameraWorldClipPlanes[5];
                    case 6: return unity_CameraProjection[0];
                    case 7: return unity_CameraProjection[1];
                    case 8: return unity_CameraProjection[2];
                    case 9: return unity_CameraProjection[3];
                    case 10: return unity_CameraInvProjection[0];
                    case 11: return unity_CameraInvProjection[1];
                    case 12: return unity_CameraInvProjection[2];
                    case 13: return unity_CameraInvProjection[3];
                    case 14: return unity_WorldToCamera[0];
                    case 15: return unity_WorldToCamera[1];
                    case 16: return unity_WorldToCamera[2];
                    case 17: return unity_WorldToCamera[3];
                    case 18: return unity_CameraToWorld[0];
                    case 19: return unity_CameraToWorld[1];
                    case 20: return unity_CameraToWorld[2];
                    case 21: return unity_CameraToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ShadowSplitSpheres[0];
                    case 1: return unity_ShadowSplitSpheres[1];
                    case 2: return unity_ShadowSplitSpheres[2];
                    case 3: return unity_ShadowSplitSpheres[3];
                    case 4: return unity_ShadowSplitSqRadii;
                    default: return (float4)0;
                }
            }
            
            Texture2D _CameraDepthTexture : register(t0);
            SamplerState sampler_CameraDepthTexture : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
                float3 v3 : TEXCOORD2;
                float3 v4 : TEXCOORD3;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                float4 v3 = (float4)0;
                float4 v4 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xyz = input.v2;
                v3.xyz = input.v3;
                v4.xyz = input.v4;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r2 = (float4)0;
                float4 r3 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
                r0_0 = _CameraDepthTexture.Sample(sampler_CameraDepthTexture, v1.xy);
                //    1: mad r0.y, cb0[7].x, r0.x, cb0[7].y
                r0_0.y = _ZBufferParams.x * r0_0.x + _ZBufferParams.y;
                //    2: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
                r0_0.y = 1.0f / r0_0.y;
                //    3: add r0.x, -r0.x, l(1.000000)
                r0_0.x = -r0_0.x + 1.0f;
                //    4: add r0.z, -r0.y, r0.x
                r0_0.z = mad(-r0_0.y, 1.0, r0_0.x);
                //    5: mad r0.y, cb0[8].w, r0.z, r0.y
                r0_0.y = unity_OrthoParams.w * r0_0.z + r0_0.y;
                //    6: mul r1.xyz, r0.yyyy, v2.xyzx
                r1_0.xyz = v2.xyz * r0_0.y;
                //    7: add r2.xyz, -v3.xyzx, v4.xyzx
                r2.xyz = -v3.xyz + v4.xyz;
                //    8: mad r0.xzw, r0.xxxx, r2.xxyz, v3.xxyz
                u_xlat_temp_x = r0_0.x * r2.x + v3.x;
                u_xlat_temp_z = r0_0.x * r2.y + v3.y;
                u_xlat_temp_w = r0_0.x * r2.z + v3.z;
                r0_0.x = u_xlat_temp_x;
                r0_0.z = u_xlat_temp_z;
                r0_0.w = u_xlat_temp_w;
                //    9: mad r0.xyz, -v2.xyzx, r0.yyyy, r0.xzwx
                r0_0.xyz = r0_0.xzw - v2.xyz * r0_0.y;
                //   10: mad r0.xyz, cb0[8].wwww, r0.xyzx, r1.xyzx
                r0_0.xyz = unity_OrthoParams.w * r0_0.xyz + r1_0.xyz;
                //   11: mul r1.xyz, r0.yyyy, cb1[19].xyzx
                r1_0.xyz = transpose(unity_CameraToWorld)[1].xyz * r0_0.y;
                //   12: mad r0.xyw, cb1[18].xyxz, r0.xxxx, r1.xyxz
                u_xlat_temp_x = transpose(unity_CameraToWorld)[0].x * r0_0.x + r1_0.x;
                u_xlat_temp_y = transpose(unity_CameraToWorld)[0].y * r0_0.x + r1_0.y;
                u_xlat_temp_w = transpose(unity_CameraToWorld)[0].z * r0_0.x + r1_0.z;
                r0_0.x = u_xlat_temp_x;
                r0_0.y = u_xlat_temp_y;
                r0_0.w = u_xlat_temp_w;
                //   13: mad r0.xyz, cb1[20].xyzx, r0.zzzz, r0.xywx
                r0_0.xyz = transpose(unity_CameraToWorld)[2].xyz * r0_0.z + r0_0.xyw;
                //   14: add r0.xyz, r0.xyzx, cb1[21].xyzx
                r0_0.xyz = transpose(unity_CameraToWorld)[3].xyz + r0_0.xyz;
                //   15: add r1.xyz, r0.xyzx, -cb2[0].xyzx
                r1_0.xyz = -unity_ShadowSplitSpheres[0].xyz + r0_0.xyz;
                //   16: add r2.xyz, r0.xyzx, -cb2[1].xyzx
                r2.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[1].xyz;
                //   17: add r3.xyz, r0.xyzx, -cb2[2].xyzx
                r3.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[2].xyz;
                //   18: add r0.xyz, r0.xyzx, -cb2[3].xyzx
                r0_0.xyz = r0_0.xyz + -unity_ShadowSplitSpheres[3].xyz;
                //   19: dp3 r1.x, r1.xyzx, r1.xyzx
                r1_0.x = dot(r1_0.xyz, r1_0.xyz);
                //   20: dp3 r1.y, r2.xyzx, r2.xyzx
                r1_0.y = dot(r2.xyz, r2.xyz);
                //   21: dp3 r1.z, r3.xyzx, r3.xyzx
                r1_0.z = dot(r3.xyz, r3.xyz);
                //   22: dp3 r1.w, r0.xyzx, r0.xyzx
                r1_0.w = dot(r0_0.xyz, r0_0.xyz);
                //   23: lt r0.xyzw, r1.xyzw, cb2[4].xyzw
                r0_1 = asfloat((r1_0 < unity_ShadowSplitSqRadii) ? 0xFFFFFFFFu : 0u);
                //   24: and r1.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r1_1 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r0_1));
                //   25: movc r0.xyz, r0.xyzx, l(-1.000000,-1.000000,-1.000000,0), l(-0.000000,-0.000000,-0.000000,0)
                r0_1.xyz = asuint(r0_1.xyz) ? float3(-1.0f, -1.0f, -1.0f) : float3(-0.0f, -0.0f, -0.0f);
                //   26: add r0.xyz, r0.xyzx, r1.yzwy
                r0_1.xyz = r1_1.yzw + r0_1.xyz;
                //   27: max r1.yzw, r0.xxyz, l(0.000000, 0.000000, 0.000000, 0.000000)
                r1_1.yzw = max(r0_1.xyz, float3(0.0f, 0.0f, 0.0f));
                //   28: dp4 r0.x, r1.xyzw, l(1.000000, 2.000000, 3.000000, 4.000000)
                r0_1.x = dot(r1_1, float4(1.0f, 2.0f, 3.0f, 4.0f));
                //   29: add r0.x, r0.x, l(-1.000000)
                r0_1.x = r0_1.x + -1.0f;
                //   30: ge r0.y, r0.x, l(0.000000)
                r0_1.y = asfloat((r0_1.x >= 0.0f) ? 0xFFFFFFFFu : 0u);
                //   31: if_nz r0.y
                [branch] if (asuint(r0_1.y)) {
                    //   32: ftou r0.x, r0.x
                    r0_1.x = asfloat((uint)(r0_1.x));
                    //   33: mov o0.xyz, icb[r0.x + 0].xyzx
                    o0.xyz = unk0_arr[asint(asint(r0_1.x)) + 0].xyz;
                    //   34: mov o0.w, l(0.500000)
                    o0.w = 0.5f;
                //   35: else
                } else {
                    //   36: mov o0.xyzw, l(1.000000,1.000000,1.000000,0)
                    o0 = float4(1.0f, 1.0f, 1.0f, 0.0f);
                //   37: endif
                }
                //   38: ret
                return o0;
                return o0;
            }
            #else
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            static const float4 unk0_arr[] = {
                float4(0.500000, 0.500000, 0.700000, 0.500000),
                float4(0.500000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.700000, 0.500000, 0.500000),
                float4(0.700000, 0.500000, 0.500000, 0.500000)
            };
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb0_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
                float4 _ZBufferParams;
                float4 unity_OrthoParams;
            };
            
            cbuffer UnityShadows : register(b1) {
                float4 unity_ShadowSplitSpheres[4];
                float4 unity_ShadowSplitSqRadii;
                float4 unity_LightShadowBias;
                float4 _LightSplitsNear;
                float4 _LightSplitsFar;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    case 7: return _ZBufferParams;
                    case 8: return unity_OrthoParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ShadowSplitSpheres[0];
                    case 1: return unity_ShadowSplitSpheres[1];
                    case 2: return unity_ShadowSplitSpheres[2];
                    case 3: return unity_ShadowSplitSpheres[3];
                    case 4: return unity_ShadowSplitSqRadii;
                    case 5: return unity_LightShadowBias;
                    case 6: return _LightSplitsNear;
                    case 7: return _LightSplitsFar;
                    default: return (float4)0;
                }
            }
            
            Texture2D _CameraDepthTexture : register(t0);
            SamplerState sampler_CameraDepthTexture : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
                float3 v3 : TEXCOORD2;
                float3 v4 : TEXCOORD3;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                float4 v3 = (float4)0;
                float4 v4 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xyz = input.v2;
                v3.xyz = input.v3;
                v4.xyz = input.v4;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v1.xyxx, t0.xyzw, s0
                r0_0 = _CameraDepthTexture.Sample(sampler_CameraDepthTexture, v1.xy);
                //    1: mad r0.y, cb0[7].x, r0.x, cb0[7].y
                r0_0.y = _ZBufferParams.x * r0_0.x + _ZBufferParams.y;
                //    2: div r0.y, l(1.000000, 1.000000, 1.000000, 1.000000), r0.y
                r0_0.y = 1.0f / r0_0.y;
                //    3: add r0.x, -r0.x, l(1.000000)
                r0_0.x = -r0_0.x + 1.0f;
                //    4: add r0.z, -r0.y, r0.x
                r0_0.z = mad(-r0_0.y, 1.0, r0_0.x);
                //    5: mad r0.y, cb0[8].w, r0.z, r0.y
                r0_0.y = unity_OrthoParams.w * r0_0.z + r0_0.y;
                //    6: mul r0.z, r0.y, v2.z
                r0_0.z = v2.z * r0_0.y;
                //    7: add r0.w, -v3.z, v4.z
                r0_0.w = -v3.z + v4.z;
                //    8: mad r0.x, r0.x, r0.w, v3.z
                r0_0.x = r0_0.x * r0_0.w + v3.z;
                //    9: mad r0.x, -v2.z, r0.y, r0.x
                r0_0.x = r0_0.x - v2.z * r0_0.y;
                //   10: mad r0.x, cb0[8].w, r0.x, r0.z
                r0_0.x = unity_OrthoParams.w * r0_0.x + r0_0.z;
                //   11: ge r1.xyzw, r0.xxxx, cb1[6].xyzw
                r1_0 = asfloat((r0_0.x >= _LightSplitsNear) ? 0xFFFFFFFFu : 0u);
                //   12: and r1.xyzw, r1.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r1_1 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r1_0));
                //   13: lt r0.xyzw, r0.xxxx, cb1[7].xyzw
                r0_1 = asfloat((r0_0.x < _LightSplitsFar) ? 0xFFFFFFFFu : 0u);
                //   14: and r0.xyzw, r0.xyzw, l(0x3f800000, 0x3f800000, 0x3f800000, 0x3f800000)
                r0_2 = asfloat(uint4(1065353216u, 1065353216u, 1065353216u, 1065353216u) & asuint(r0_1));
                //   15: mul r0.xyzw, r0.xyzw, r1.xyzw
                r0_3 = r1_1 * r0_2;
                //   16: dp4 r0.x, r0.xyzw, l(1.000000, 2.000000, 3.000000, 4.000000)
                r0_3.x = dot(r0_3, float4(1.0f, 2.0f, 3.0f, 4.0f));
                //   17: add r0.x, r0.x, l(-1.000000)
                r0_3.x = r0_3.x + -1.0f;
                //   18: ge r0.y, r0.x, l(0.000000)
                r0_3.y = asfloat((r0_3.x >= 0.0f) ? 0xFFFFFFFFu : 0u);
                //   19: if_nz r0.y
                [branch] if (asuint(r0_3.y)) {
                    //   20: ftou r0.x, r0.x
                    r0_3.x = asfloat((uint)(r0_3.x));
                    //   21: mov o0.xyz, icb[r0.x + 0].xyzx
                    o0.xyz = unk0_arr[asint(asint(r0_3.x)) + 0].xyz;
                    //   22: mov o0.w, l(0.500000)
                    o0.w = 0.5f;
                //   23: else
                } else {
                    //   24: mov o0.xyzw, l(1.000000,1.000000,1.000000,0)
                    o0 = float4(1.0f, 1.0f, 1.0f, 0.0f);
                //   25: endif
                }
                //   26: ret
                return o0;
                return o0;
            }
            #endif

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

