// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "DXBCTests/3_Math"
{
    Properties
    {
    }

    SubShader
    {
        Pass
        {
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 3.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerDraw : register(b0) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b1) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float3 v1 : NORMAL;
                float4 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float3 o1 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyz = input.v1;
                v2.xyzw = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb0[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o1.xyz, v1.xyzx
                o1.xyz = v1.xyz;
                //    9: ret
                output.o0 = o0;
                output.o1 = o1.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1.xyz;
                return output;
            }

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            cbuffer UnityPerCamera : register(b0) {
                float4 _Time;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    default: return (float4)0;
                }
            }
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float3 v1 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyz = input.v1;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sincos r0.x, null, cb0[0].y
                    float sincos_cos_temp;
                sincos(_Time.y, r0_0.x, sincos_cos_temp);
                //    1: sincos null, r0.y, cb0[0].x
                    float sincos_sin_temp;
                sincos(_Time.x, sincos_sin_temp, r0_0.y);
                //    2: mul o0.z, r0.y, r0.x
                o0.z = r0_0.x * r0_0.y;
                //    3: dp3 r0.x, v1.xyzx, v1.xyzx
                r0_1.x = dot(v1.xyz, v1.xyz);
                //    4: rsq r0.x, r0.x
                r0_1.x = rsqrt(r0_1.x);
                //    5: mul r0.xy, r0.xxxx, v1.xyxx
                r0_1.xy = v1.xy * r0_1.x;
                //    6: dp2 r0.x, r0.xyxx, l(0.707107, 0.707107, 0.000000, 0.000000)
                r0_1.x = dot(r0_1.xy, float2(0.707106769f, 0.707106769f));
                //    7: add r0.y, |r0.x|, l(0.010000)
                r0_1.y = abs(r0_1.x) + 0.00999999978f;
                //    8: mov_sat o0.x, r0.x
                o0.x = saturate(r0_1.x);
                //    9: rsq o0.y, r0.y
                o0.y = rsqrt(r0_1.y);
                //   10: mov o0.w, l(1.000000)
                o0.w = 1.0f;
                //   11: ret
                return o0;
                return o0;
            }

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

