// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "DXBCTests/1_PropertyMap"
{
    Properties
    {
        _MainColor ("Color", Color) = (1,1,1,1)
        _Scale ("Scale", Float) = 1
        _Offset ("Offset", Vector) = (0,0,0,0)
        _Threshold ("Range", Range(0, 1)) = 0.5
    }

    SubShader
    {
        Pass
        {
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 4.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 cb0_2;
                float _Scale;
                float3 cb0_pad_52;
                float4 _Offset;
            
            cbuffer UnityPerDraw : register(b1) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b2) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return (float4)0;
                    case 3: return float4(_Scale, 0.0f, 0.0f, 0.0f);
                    case 4: return _Offset;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                v0.xyzw = input.v0;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mad r0.xyz, v0.xyzx, cb0[3].xxxx, cb0[4].xyzx
                r0_0.xyz = v0.xyz * _Scale + _Offset.xyz;
                //    1: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
                r1_0 = transpose(unity_ObjectToWorld)[1] * r0_0.y;
                //    2: mad r1.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_ObjectToWorld)[0] * r0_0.x + r1_0;
                //    3: mad r0.xyzw, cb1[2].xyzw, r0.zzzz, r1.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[2] * r0_0.z + r1_1;
                //    4: add r0.xyzw, r0.xyzw, cb1[3].xyzw
                r0_2 = transpose(unity_ObjectToWorld)[3] + r0_1;
                //    5: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
                r1_2 = transpose(unity_MatrixVP)[1] * r0_2.y;
                //    6: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
                r1_3 = transpose(unity_MatrixVP)[0] * r0_2.x + r1_2;
                //    7: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
                r1_4 = transpose(unity_MatrixVP)[2] * r0_2.z + r1_3;
                //    8: mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_2.w + r1_4;
                //    9: ret
                output.o0 = o0;
                return output;
                output.o0 = o0;
                return output;
            }

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _MainColor;
                float4 cb0_3;
                float4 cb0_4;
                float _Threshold;
                float3 cb0_pad_84;
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _MainColor;
                    case 3: return (float4)0;
                    case 4: return (float4)0;
                    case 5: return float4(_Threshold, 0.0f, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            struct ps_input {
                float4 v0 : SV_POSITION;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                v0.xyzw = input.v0;
                float4 o0 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul o0.xyzw, cb0[2].xyzw, cb0[5].xxxx
                o0 = _Threshold * _MainColor;
                //    1: ret
                return o0;
                return o0;
            }

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

