// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "DXBCTests/2_Texture"
{
    Properties
    {
        _MainTex ("Texture 2D", 2D) = "white" {}
        _CubeTex ("Cubemap", Cube) = "white" {}
        _VolTex ("Volume 3D", 3D) = "white" {}
    }

    SubShader
    {
        Pass
        {
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 3.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
            cbuffer UnityPerDraw : register(b0) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b1) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float3 v1 : NORMAL;
                float4 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float2 o1 : TEXCOORD0;
                float3 o2 : TEXCOORD1;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyz = input.v1;
                v2.xyzw = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xyzw, v0.yyyy, cb0[1].xyzw
                r0_0 = transpose(unity_ObjectToWorld)[1] * v0.y;
                //    1: mad r0.xyzw, cb0[0].xyzw, v0.xxxx, r0.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * v0.x + r0_0;
                //    2: mad r0.xyzw, cb0[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    3: add r0.xyzw, r0.xyzw, cb0[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    4: mul r1.xyzw, r0.yyyy, cb1[18].xyzw
                r1_0 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    5: mad r1.xyzw, cb1[17].xyzw, r0.xxxx, r1.xyzw
                r1_1 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_0;
                //    6: mad r1.xyzw, cb1[19].xyzw, r0.zzzz, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_1;
                //    7: mad o0.xyzw, cb1[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_2;
                //    8: mov o1.xy, v2.xyxx
                o1.xy = v2.xy;
                //    9: mov o2.xyz, v1.xyzx
                o2.xyz = v1.xyz;
                //   10: ret
                output.o0 = o0;
                output.o1 = o1.xy;
                output.o2 = o2.xyz;
                return output;
                output.o0 = o0;
                output.o1 = o1.xy;
                output.o2 = o2.xyz;
                return output;
            }

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            // No keyword variants
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            Texture2D _MainTex : register(t0);
            TextureCube _CubeTex : register(t1);
            Texture3D _VolTex : register(t2);
            SamplerState sampler_MainTex : register(s0);
            SamplerState sampler_CubeTex : register(s1);
            SamplerState sampler_VolTex : register(s2);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float2 v1 : TEXCOORD0;
                float3 v2 : TEXCOORD1;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xy = input.v1;
                v2.xyz = input.v2;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r2 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mov r0.xy, v1.xyxx
                r0_0.xy = v1.xy;
                //    1: mov r0.z, l(0.500000)
                r0_0.z = 0.5f;
                //    2: sample r0.xyzw, r0.xyzx, t2.xyzw, s2
                r0_1 = _VolTex.Sample(sampler_VolTex, r0_0.xyz);
                //    3: sample r1.xyzw, v1.xyxx, t0.xyzw, s0
                r1_0 = _MainTex.Sample(sampler_MainTex, v1.xy);
                //    4: sample r2.xyzw, v2.xyzx, t1.xyzw, s1
                r2 = _CubeTex.Sample(sampler_CubeTex, v2.xyz);
                //    5: add r1.xyzw, r1.xyzw, r2.xyzw
                r1_1 = r2 + r1_0;
                //    6: add r0.xyzw, r0.xyzw, r1.xyzw
                r0_2 = r1_1 + r0_1;
                //    7: mul o0.xyzw, r0.xyzw, l(0.333333, 0.333333, 0.333333, 0.333333)
                o0 = r0_2 * float4(0.333333343f, 0.333333343f, 0.333333343f, 0.333333343f);
                //    8: ret
                return o0;
                return o0;
            }

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

