// Auto-generated ShaderLab from DXBCSandbox C-emitter
Shader "Sprites/Default"
{
    Properties
    {
        [PerRendererData] _MainTex ("Sprite Texture", 2D) = "white" {}
        _Color ("Tint", Color) = (1,1,1,1)
        [MaterialToggle] PixelSnap ("Pixel snap", Float) = 0
        [HideInInspector] _RendererColor ("RendererColor", Color) = (1,1,1,1)
        [HideInInspector] _Flip ("Flip", Vector) = (1,1,1,1)
        [PerRendererData] _AlphaTex ("External Alpha", 2D) = "white" {}
        [PerRendererData] _EnableExternalAlpha ("Enable External Alpha", Float) = 0
    }

    SubShader
    {
        Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
        Pass
        {
            Tags { "CanUseSpriteAtlas"="true" "IGNOREPROJECTOR"="true" "PreviewType"="Plane" "QUEUE"="Transparent" "RenderType"="Transparent" }
            Cull Off
            ZWrite Off
            Blend One OneMinusSrcAlpha
            HLSLPROGRAM
            #if !defined(VERTEX) && !defined(FRAGMENT) && !defined(SHADER_STAGE_VERTEX) && !defined(SHADER_STAGE_FRAGMENT)
            #define VERTEX 1
            #define FRAGMENT 1
            #endif

            #pragma vertex vert
            #pragma fragment frag
            #pragma target 3.0
            #define UNITY_SHADER_VARIABLES_INCLUDED
            #define UNIVERSAL_SHADER_VARIABLES_INCLUDED

            #if defined(VERTEX) || defined(SHADER_STAGE_VERTEX)
            #if defined(PIXELSNAP_ON)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _Color;
            
            cbuffer UnityPerCamera : register(b1) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb1_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            cbuffer UnityPerDrawSprite : register(b4) {
                float4 _RendererColor : packoffset(c0);
                float2 _Flip : packoffset(c1);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _Color;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb4(int idx) {
                switch(idx) {
                    case 0: return _RendererColor;
                    case 1: return float4(_Flip, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : COLOR;
                float2 o2 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r0_5 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xy, v0.xyxx, cb4[1].xyxx
                r0_0.xy = v0.xy * _Flip;
                //    1: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
                r1_0 = transpose(unity_ObjectToWorld)[1] * r0_0.y;
                //    2: mad r0.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * r0_0.x + r1_0;
                //    3: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    4: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    5: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_1 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    6: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_1;
                //    7: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_3 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_2;
                //    8: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_3;
                //    9: div r0.xy, r0.xyxx, r0.wwww
                r0_4.xy = r0_4.xy / r0_4.w;
                //   10: mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
                r1_4.xy = _ScreenParams.xy * float2(0.5f, 0.5f);
                //   11: mul r0.xy, r0.xyxx, r1.xyxx
                r0_4.xy = r1_4.xy * r0_4.xy;
                //   12: round_ne r0.xy, r0.xyxx
                r0_4.xy = round(r0_4.xy);
                //   13: div r0.xy, r0.xyxx, r1.xyxx
                r0_4.xy = r0_4.xy / r1_4.xy;
                //   14: mul o0.xy, r0.wwww, r0.xyxx
                o0.xy = r0_4.xy * r0_4.w;
                //   15: mov o0.zw, r0.zzzw
                o0.zw = r0_4.zw;
                //   16: mul r0.xyzw, v1.xyzw, cb0[2].xyzw
                r0_5 = v1 * _Color;
                //   17: mul o1.xyzw, r0.xyzw, cb4[0].xyzw
                o1 = _RendererColor * r0_5;
                //   18: mov o2.xy, v2.xyxx
                o2.xy = v2.xy;
                //   19: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
            }
            #elif defined(ETC1_EXTERNAL_ALPHA)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _Color;
            
            cbuffer UnityPerDraw : register(b1) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b2) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            cbuffer UnityPerDrawSprite : register(b3) {
                float4 _RendererColor : packoffset(c0);
                float2 _Flip : packoffset(c1);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _Color;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return _RendererColor;
                    case 1: return float4(_Flip, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : COLOR;
                float2 o2 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xy, v0.xyxx, cb3[1].xyxx
                r0_0.xy = v0.xy * _Flip;
                //    1: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
                r1_0 = transpose(unity_ObjectToWorld)[1] * r0_0.y;
                //    2: mad r0.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * r0_0.x + r1_0;
                //    3: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    4: add r0.xyzw, r0.xyzw, cb1[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    5: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
                r1_1 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    6: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_1;
                //    7: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
                r1_3 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_2;
                //    8: mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_3;
                //    9: mul r0.xyzw, v1.xyzw, cb0[2].xyzw
                r0_4 = v1 * _Color;
                //   10: mul o1.xyzw, r0.xyzw, cb3[0].xyzw
                o1 = _RendererColor * r0_4;
                //   11: mov o2.xy, v2.xyxx
                o2.xy = v2.xy;
                //   12: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
            }
            #elif defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON)
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _Color;
            
            cbuffer UnityPerCamera : register(b1) {
                float4 _Time;
                float4 _SinTime;
                float4 _CosTime;
                float4 unity_DeltaTime;
                float3 _WorldSpaceCameraPos;
                float cb1_pad_76;
                float4 _ProjectionParams;
                float4 _ScreenParams;
            };
            
            cbuffer UnityPerDraw : register(b2) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b3) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            cbuffer UnityPerDrawSprite : register(b4) {
                float4 _RendererColor : packoffset(c0);
                float2 _Flip : packoffset(c1);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _Color;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return _Time;
                    case 1: return _SinTime;
                    case 2: return _CosTime;
                    case 3: return unity_DeltaTime;
                    case 4: return float4(_WorldSpaceCameraPos, 0.0f);
                    case 5: return _ProjectionParams;
                    case 6: return _ScreenParams;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb4(int idx) {
                switch(idx) {
                    case 0: return _RendererColor;
                    case 1: return float4(_Flip, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : COLOR;
                float2 o2 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r0_5 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float4 r1_4 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xy, v0.xyxx, cb4[1].xyxx
                r0_0.xy = v0.xy * _Flip;
                //    1: mul r1.xyzw, r0.yyyy, cb2[1].xyzw
                r1_0 = transpose(unity_ObjectToWorld)[1] * r0_0.y;
                //    2: mad r0.xyzw, cb2[0].xyzw, r0.xxxx, r1.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * r0_0.x + r1_0;
                //    3: mad r0.xyzw, cb2[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    4: add r0.xyzw, r0.xyzw, cb2[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    5: mul r1.xyzw, r0.yyyy, cb3[18].xyzw
                r1_1 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    6: mad r1.xyzw, cb3[17].xyzw, r0.xxxx, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_1;
                //    7: mad r1.xyzw, cb3[19].xyzw, r0.zzzz, r1.xyzw
                r1_3 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_2;
                //    8: mad r0.xyzw, cb3[20].xyzw, r0.wwww, r1.xyzw
                r0_4 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_3;
                //    9: div r0.xy, r0.xyxx, r0.wwww
                r0_4.xy = r0_4.xy / r0_4.w;
                //   10: mul r1.xy, cb1[6].xyxx, l(0.500000, 0.500000, 0.000000, 0.000000)
                r1_4.xy = _ScreenParams.xy * float2(0.5f, 0.5f);
                //   11: mul r0.xy, r0.xyxx, r1.xyxx
                r0_4.xy = r1_4.xy * r0_4.xy;
                //   12: round_ne r0.xy, r0.xyxx
                r0_4.xy = round(r0_4.xy);
                //   13: div r0.xy, r0.xyxx, r1.xyxx
                r0_4.xy = r0_4.xy / r1_4.xy;
                //   14: mul o0.xy, r0.wwww, r0.xyxx
                o0.xy = r0_4.xy * r0_4.w;
                //   15: mov o0.zw, r0.zzzw
                o0.zw = r0_4.zw;
                //   16: mul r0.xyzw, v1.xyzw, cb0[2].xyzw
                r0_5 = v1 * _Color;
                //   17: mul o1.xyzw, r0.xyzw, cb4[0].xyzw
                o1 = _RendererColor * r0_5;
                //   18: mov o2.xy, v2.xyxx
                o2.xy = v2.xy;
                //   19: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
            }
            #else
            // Generated by DXBCSandbox
            // Model: vs_4_0
            
                float4 cb0_0;
                float4 cb0_1;
                float4 _Color;
            
            cbuffer UnityPerDraw : register(b1) {
                float4x4 unity_ObjectToWorld;
            };
            
            cbuffer UnityPerFrame : register(b2) {
                float4 glstate_lightmodel_ambient;
                float4 unity_AmbientSky;
                float4 unity_AmbientEquator;
                float4 unity_AmbientGround;
                float4 unity_IndirectSpecColor;
                float4x4 glstate_matrix_projection;
                float4x4 unity_MatrixV;
                float4x4 unity_MatrixInvV;
                float4x4 unity_MatrixVP;
            };
            
            cbuffer UnityPerDrawSprite : register(b3) {
                float4 _RendererColor : packoffset(c0);
                float2 _Flip : packoffset(c1);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return (float4)0;
                    case 2: return _Color;
                    default: return (float4)0;
                }
            }
            
            float4 get_cb1(int idx) {
                switch(idx) {
                    case 0: return unity_ObjectToWorld[0];
                    case 1: return unity_ObjectToWorld[1];
                    case 2: return unity_ObjectToWorld[2];
                    case 3: return unity_ObjectToWorld[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb2(int idx) {
                switch(idx) {
                    case 0: return glstate_lightmodel_ambient;
                    case 1: return unity_AmbientSky;
                    case 2: return unity_AmbientEquator;
                    case 3: return unity_AmbientGround;
                    case 4: return unity_IndirectSpecColor;
                    case 5: return glstate_matrix_projection[0];
                    case 6: return glstate_matrix_projection[1];
                    case 7: return glstate_matrix_projection[2];
                    case 8: return glstate_matrix_projection[3];
                    case 9: return unity_MatrixV[0];
                    case 10: return unity_MatrixV[1];
                    case 11: return unity_MatrixV[2];
                    case 12: return unity_MatrixV[3];
                    case 13: return unity_MatrixInvV[0];
                    case 14: return unity_MatrixInvV[1];
                    case 15: return unity_MatrixInvV[2];
                    case 16: return unity_MatrixInvV[3];
                    case 17: return unity_MatrixVP[0];
                    case 18: return unity_MatrixVP[1];
                    case 19: return unity_MatrixVP[2];
                    case 20: return unity_MatrixVP[3];
                    default: return (float4)0;
                }
            }
            
            float4 get_cb3(int idx) {
                switch(idx) {
                    case 0: return _RendererColor;
                    case 1: return float4(_Flip, 0.0f, 0.0f);
                    default: return (float4)0;
                }
            }
            
            struct appdata {
                float4 v0 : POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            struct v2f {
                float4 o0 : SV_POSITION;
                float4 o1 : COLOR;
                float2 o2 : TEXCOORD0;
            };
            
            v2f vert(appdata input) {
                v2f output;
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 o1 = (float4)0;
                float4 o2 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r0_2 = (float4)0;
                float4 r0_3 = (float4)0;
                float4 r0_4 = (float4)0;
                float4 r1_0 = (float4)0;
                float4 r1_1 = (float4)0;
                float4 r1_2 = (float4)0;
                float4 r1_3 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: mul r0.xy, v0.xyxx, cb3[1].xyxx
                r0_0.xy = v0.xy * _Flip;
                //    1: mul r1.xyzw, r0.yyyy, cb1[1].xyzw
                r1_0 = transpose(unity_ObjectToWorld)[1] * r0_0.y;
                //    2: mad r0.xyzw, cb1[0].xyzw, r0.xxxx, r1.xyzw
                r0_1 = transpose(unity_ObjectToWorld)[0] * r0_0.x + r1_0;
                //    3: mad r0.xyzw, cb1[2].xyzw, v0.zzzz, r0.xyzw
                r0_2 = transpose(unity_ObjectToWorld)[2] * v0.z + r0_1;
                //    4: add r0.xyzw, r0.xyzw, cb1[3].xyzw
                r0_3 = transpose(unity_ObjectToWorld)[3] + r0_2;
                //    5: mul r1.xyzw, r0.yyyy, cb2[18].xyzw
                r1_1 = transpose(unity_MatrixVP)[1] * r0_3.y;
                //    6: mad r1.xyzw, cb2[17].xyzw, r0.xxxx, r1.xyzw
                r1_2 = transpose(unity_MatrixVP)[0] * r0_3.x + r1_1;
                //    7: mad r1.xyzw, cb2[19].xyzw, r0.zzzz, r1.xyzw
                r1_3 = transpose(unity_MatrixVP)[2] * r0_3.z + r1_2;
                //    8: mad o0.xyzw, cb2[20].xyzw, r0.wwww, r1.xyzw
                o0 = transpose(unity_MatrixVP)[3] * r0_3.w + r1_3;
                //    9: mul r0.xyzw, v1.xyzw, cb0[2].xyzw
                r0_4 = v1 * _Color;
                //   10: mul o1.xyzw, r0.xyzw, cb3[0].xyzw
                o1 = _RendererColor * r0_4;
                //   11: mov o2.xy, v2.xyxx
                o2.xy = v2.xy;
                //   12: ret
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
                output.o0 = o0;
                output.o1 = o1;
                output.o2 = o2.xy;
                return output;
            }
            #endif

            #endif

            #if defined(FRAGMENT) || defined(SHADER_STAGE_FRAGMENT)
            #if defined(PIXELSNAP_ON)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            Texture2D _MainTex : register(t0);
            SamplerState sampler_MainTex : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v2.xyxx, t0.xyzw, s0
                r0_0 = _MainTex.Sample(sampler_MainTex, v2.xy);
                //    1: mul r0.xyzw, r0.xyzw, v1.xyzw
                r0_1 = v1 * r0_0;
                //    2: mul o0.xyz, r0.wwww, r0.xyzx
                u_xlat_temp_x = r0_1.x * r0_1.w;
                u_xlat_temp_y = r0_1.y * r0_1.w;
                u_xlat_temp_z = r0_1.z * r0_1.w;
                o0.xyz = float3(u_xlat_temp_x, u_xlat_temp_y, u_xlat_temp_z);
                //    3: mov o0.w, r0.w
                o0.w = r0_1.w;
                //    4: ret
                return o0;
                return o0;
            }
            #elif defined(ETC1_EXTERNAL_ALPHA)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            cbuffer UnityPerDrawSprite : register(b0) {
                float _EnableExternalAlpha : packoffset(c1.z);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return float4(0.0f, 0.0f, _EnableExternalAlpha, 0.0f);
                    default: return (float4)0;
                }
            }
            
            Texture2D _MainTex : register(t0);
            Texture2D _AlphaTex : register(t1);
            SamplerState sampler_MainTex : register(s0);
            SamplerState sampler_AlphaTex : register(s1);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v2.xyxx, t1.xyzw, s1
                r0_0 = _AlphaTex.Sample(sampler_AlphaTex, v2.xy);
                //    1: sample r1.xyzw, v2.xyxx, t0.xyzw, s0
                r1 = _MainTex.Sample(sampler_MainTex, v2.xy);
                //    2: add r0.x, r0.x, -r1.w
                r0_0.x = -r1.w + r0_0.x;
                //    3: mad r1.w, cb0[1].z, r0.x, r1.w
                r1.w = _EnableExternalAlpha * r0_0.x + r1.w;
                //    4: mul r0.xyzw, r1.xyzw, v1.xyzw
                r0_1 = v1 * r1;
                //    5: mul o0.xyz, r0.wwww, r0.xyzx
                u_xlat_temp_x = r0_1.x * r0_1.w;
                u_xlat_temp_y = r0_1.y * r0_1.w;
                u_xlat_temp_z = r0_1.z * r0_1.w;
                o0.xyz = float3(u_xlat_temp_x, u_xlat_temp_y, u_xlat_temp_z);
                //    6: mov o0.w, r0.w
                o0.w = r0_1.w;
                //    7: ret
                return o0;
                return o0;
            }
            #elif defined(ETC1_EXTERNAL_ALPHA) && defined(PIXELSNAP_ON)
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            cbuffer UnityPerDrawSprite : register(b0) {
                float _EnableExternalAlpha : packoffset(c1.z);
            };
            
            float4 get_cb0(int idx) {
                switch(idx) {
                    case 0: return (float4)0;
                    case 1: return float4(0.0f, 0.0f, _EnableExternalAlpha, 0.0f);
                    default: return (float4)0;
                }
            }
            
            Texture2D _MainTex : register(t0);
            Texture2D _AlphaTex : register(t1);
            SamplerState sampler_MainTex : register(s0);
            SamplerState sampler_AlphaTex : register(s1);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float4 r1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v2.xyxx, t1.xyzw, s1
                r0_0 = _AlphaTex.Sample(sampler_AlphaTex, v2.xy);
                //    1: sample r1.xyzw, v2.xyxx, t0.xyzw, s0
                r1 = _MainTex.Sample(sampler_MainTex, v2.xy);
                //    2: add r0.x, r0.x, -r1.w
                r0_0.x = -r1.w + r0_0.x;
                //    3: mad r1.w, cb0[1].z, r0.x, r1.w
                r1.w = _EnableExternalAlpha * r0_0.x + r1.w;
                //    4: mul r0.xyzw, r1.xyzw, v1.xyzw
                r0_1 = v1 * r1;
                //    5: mul o0.xyz, r0.wwww, r0.xyzx
                u_xlat_temp_x = r0_1.x * r0_1.w;
                u_xlat_temp_y = r0_1.y * r0_1.w;
                u_xlat_temp_z = r0_1.z * r0_1.w;
                o0.xyz = float3(u_xlat_temp_x, u_xlat_temp_y, u_xlat_temp_z);
                //    6: mov o0.w, r0.w
                o0.w = r0_1.w;
                //    7: ret
                return o0;
                return o0;
            }
            #else
            // Generated by DXBCSandbox
            // Model: ps_4_0
            
            Texture2D _MainTex : register(t0);
            SamplerState sampler_MainTex : register(s0);
            
            struct ps_input {
                float4 v0 : SV_POSITION;
                float4 v1 : COLOR;
                float2 v2 : TEXCOORD0;
            };
            
            float4 frag(ps_input input) : SV_Target {
                float4 v0 = (float4)0;
                float4 v1 = (float4)0;
                float4 v2 = (float4)0;
                v0.xyzw = input.v0;
                v1.xyzw = input.v1;
                v2.xy = input.v2;
                float4 o0 = (float4)0;
                float4 r0_0 = (float4)0;
                float4 r0_1 = (float4)0;
                float u_xlat_temp_x = 0.0f;
                float u_xlat_temp_y = 0.0f;
                float u_xlat_temp_z = 0.0f;
                float u_xlat_temp_w = 0.0f;
            
                //    0: sample r0.xyzw, v2.xyxx, t0.xyzw, s0
                r0_0 = _MainTex.Sample(sampler_MainTex, v2.xy);
                //    1: mul r0.xyzw, r0.xyzw, v1.xyzw
                r0_1 = v1 * r0_0;
                //    2: mul o0.xyz, r0.wwww, r0.xyzx
                u_xlat_temp_x = r0_1.x * r0_1.w;
                u_xlat_temp_y = r0_1.y * r0_1.w;
                u_xlat_temp_z = r0_1.z * r0_1.w;
                o0.xyz = float3(u_xlat_temp_x, u_xlat_temp_y, u_xlat_temp_z);
                //    3: mov o0.w, r0.w
                o0.w = r0_1.w;
                //    4: ret
                return o0;
                return o0;
            }
            #endif

            #endif

            ENDHLSL
        }
    }
    Fallback Off
}

